import type {Metadata} from "next";
import {Header,Footer} from "../components";

export const metadata:Metadata={
  title:"Privacy Policy",
  description:"Privacy policy and terms governing inlingua Online Learning Services, personal information, cookies, accounts, and intellectual property.",
  alternates:{canonical:"/privacy-policy"},
};

export default function PrivacyPolicyPage(){return <><Header/><main id="main" className="policy-page">
  <header className="policy-hero"><div className="shell"><p className="eyebrow">LEGAL &amp; PRIVACY</p><h1>Privacy Policy</h1><p>inlingua Language School of Boston · inlingua International network</p></div></header>
  <article className="policy-content shell">
    <section><h2>Preamble</h2><p>These terms and this Privacy Policy (the “Terms”) govern the online learning services made available by inlingua (the “Online Learning Services”), whether those services are delivered through a local inlingua language center (the “Center”) or directly by inlingua. These Terms apply to the User’s access to and use of the Online Learning Services unless they are varied by a separate written agreement signed by an authorized representative of inlingua or the applicable Center.</p><p>Services booked for in-person delivery at a Center are additionally governed by that Center’s own terms and conditions. A Center’s terms take precedence over these Terms only where the Center’s terms expressly state that a specific provision is intended to prevail.</p></section>

    <section><h2>1. Access to Services</h2><h3>1.1 Place of provision</h3><p>The Online Learning Services are provided online. The User chooses the location from which the User accesses them and remains responsible for ensuring that the chosen location is suitable. A local Center may make additional local services available under separate arrangements.</p><h3>1.2 Use of services</h3><p>The User must register for or book the Online Learning Services in accordance with the instructions provided by the applicable Center or on the relevant inlingua website (the “Website”). Following registration, the User receives personal access credentials, including a login and password. Subject to availability and these Terms, the Online Learning Services may be accessed 24 hours a day, seven days a week.</p><p>Access may be interrupted temporarily for maintenance, upgrades, security work, technical corrections, or other operational reasons. No compensation is owed for such interruptions. inlingua is not responsible for access problems resulting from the User’s failure to meet the minimum hardware, software, connectivity, browser, audio, video, or other technical requirements communicated for the Online Learning Services.</p></section>

    <section><h2>2. Confidentiality – protection of personal privacy</h2><p>inlingua processes personal information in accordance with applicable data-protection requirements, including Regulation (EU) 2016/679 (the European Union General Data Protection Regulation, or “GDPR”) and the Swiss Federal Act on Data Protection, to the extent those laws apply to the relevant processing activity.</p><p>inlingua uses administrative, technical, and organizational safeguards designed to protect personal information. These safeguards may include security and vulnerability scans, software audits, firewalls, access controls, and Secure Sockets Layer (SSL) encryption for information transmitted through supported Website functions.</p><p>To the maximum extent permitted by applicable law, inlingua is not liable for indirect, incidental, consequential, or similar damages, or for delays in accessing the Online Learning Services. A User who identifies a fraudulent or unauthorized credit-card charge associated with an inlingua transaction should promptly contact inlingua and the User’s credit-card provider. No method of transmission over the internet or electronic storage is completely secure, and inlingua cannot guarantee absolute security.</p></section>

    <section><h2>3. Protection of Children’s Information</h2><p>The Website and Online Learning Services are intended for a general adult audience and are not directed to children under 18 years of age. inlingua does not knowingly collect personal information from a person under 18 without the permission of that person’s parent or legal guardian. A parent or guardian who believes that a minor has supplied personal information without authorization should contact inlingua.</p></section>

    <section><h2>4. Registration and Personal Profile</h2><p>The User must provide information that is true, accurate, complete, and current. The User must not register under a false identity or impersonate another person and must promptly update any information that becomes inaccurate or incomplete.</p><p>Access is personal and non-transferable. The User is responsible for protecting the User’s identifier and password and for activity conducted through the User’s account. The User must not disclose, assign, sell, lend, or otherwise transfer access credentials to another person.</p><p>Depending on the services selected, the User’s profile may include:</p><ul><li>First name and last name</li><li>Username and password</li><li>Email address and telephone number</li><li>Gender and date of birth</li><li>Country code</li><li>City address and address line 2</li><li>Province and region</li><li>Interface language and time zone</li><li>Skype ID</li></ul><p>Profile information is visible only to authorized administrators and, where applicable, the responsible company supervisor.</p><p>Personal information may be used to:</p><ul><li>Provide, administer, personalize, and bill for the Online Learning Services;</li><li>Create and manage the User’s account and provide customer or technical support;</li><li>Contact the User regarding bookings, learning activities, payments, changes, or inquiries;</li><li>Conduct research and statistical analysis;</li><li>Maintain, evaluate, and improve the Website and Online Learning Services;</li><li>Enforce these Terms and protect the security and integrity of the services;</li><li>Operate, administer, and manage inlingua’s business; and</li><li>Fulfill other purposes disclosed to the User at the time information is collected.</li></ul><p>The User may amend account information through the available profile controls or by contacting Customer Service or the applicable Center. The User may request deletion of the account, subject to legal, contractual, security, and record-retention requirements. Account deletion does not create a right to a refund for services that have not yet been delivered. Once deletion is completed, the User’s account information and learning data may not be recoverable. Personal information is retained while the account remains active and thereafter only for as long as reasonably necessary to provide services, resolve disputes, enforce agreements, or comply with legal obligations.</p></section>

    <section><h2>5. Who inlingua Shares the User’s Information With</h2><p>inlingua may disclose personal information to third-party service providers that perform functions such as payment processing, hosting, technical support, and customer service. Such providers are authorized to use the information only as necessary to provide the contracted services or as otherwise required by law.</p><p>Information may be shared with the local Center responsible for the User’s registration or service delivery. Pedagogical information, including placement information, progress reports, attendance information, and test results, may be shared with trainers assigned to the User when necessary for teaching and program administration.</p><p>inlingua may disclose information when required by subpoena, court order, applicable law, fraud or security investigation, governmental request, or where disclosure is reasonably necessary to protect the rights, property, safety, or legitimate interests of inlingua, its Centers, Users, personnel, or others.</p><p>If inlingua is involved in a merger, acquisition, financing, reorganization, insolvency proceeding, or sale of all or part of its assets, personal information may be transferred as part of that transaction. Where required by law, the User will be notified of any resulting material change in ownership, use, or control of personal information. Information will be disclosed to other third parties only with the User’s prior consent, unless another lawful basis permits or requires the disclosure.</p></section>

    <section><h2>6. Use of Cookies</h2><p>The Website may use cookies and similar technologies, including Google Analytics cookies, to understand how Users interact with the Website. Information generated by Google Analytics cookies, which may include the User’s IP address, may be transmitted to and stored by Google on servers in the United States. Google may use this information to evaluate Website activity, prepare reports, and provide related analytics services, and may share the information where required by law or with service providers acting on Google’s behalf.</p><p>The User may restrict or disable cookies through the User’s browser settings, although doing so may affect Website functionality. The User may also prevent Google Analytics from collecting information by installing the <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer">Google Analytics Opt-out Browser Add-on</a>.</p></section>

    <section><h2>7. Log Files</h2><p>The Website may automatically collect technical and usage information, including IP address, browser type, internet service provider, referring and exit pages, operating system, date and time stamps, and clickstream data. This information is used to analyze trends, administer and secure the Website, diagnose technical issues, understand usage, and improve the Website and Online Learning Services.</p></section>

    <section><h2>8. Abusive Behaviour</h2><p>A User who behaves disrespectfully, abusively, threateningly, or aggressively toward trainers, staff, service providers, other Users, or representatives of a Center may be immediately suspended or disconnected from the Online Learning Services. Where service is terminated for abusive behaviour, no refund will be provided.</p></section>

    <section><h2>9. Links to Other Websites</h2><p>The Website may contain links to websites operated by third parties. inlingua does not control and is not responsible for the privacy, security, content, or data practices of those websites. The User should review the privacy policies and terms of each third-party website before providing personal information.</p></section>

    <section><h2>10. Testimonials</h2><p>inlingua may publish a testimonial containing personally identifiable information only after obtaining the individual’s prior written consent. A person who wishes to have a testimonial removed may submit a request to Customer Service or the applicable Center.</p></section>

    <section><h2>11. Communications from the Website</h2><p>The User may unsubscribe from promotional or marketing emails by using the unsubscribe link contained in the relevant message. Service-related announcements, including maintenance notices, security messages, booking information, and material account updates, are part of the Online Learning Services and cannot ordinarily be declined while the account remains active. The User may stop receiving such announcements by deactivating the account, subject to applicable legal and service obligations.</p></section>

    <section><h2>12. Content of Services</h2><p>The educational content, features, learning formats, and other elements of the Online Learning Services are described on the main inlingua website and, where applicable, by the local Center. The applicable service description forms part of the User’s booking or registration arrangement.</p></section>

    <section><h2>13. Enforcement</h2><p>inlingua monitors ongoing compliance with its applicable privacy directive and these Terms and may investigate complaints, suspected misuse, security events, or other potential violations. Appropriate corrective action may be taken where non-compliance is identified.</p></section>

    <section><h2>14. Changes to the Privacy Policy</h2><p>inlingua may amend this Privacy Policy from time to time. Where a change is material, inlingua will notify affected Users by email or by a prominent notice on the Website before the change takes effect, where required. The User is encouraged to review this page periodically for the current version.</p></section>

    <section><h2>15. Contact inlingua</h2><p>Questions, requests, or complaints relating to these Terms or personal information may be directed to the applicable local Center or to:</p><address><strong>inlingua International Ltd</strong><br/>Belpstrasse 11<br/>CH-3007 Bern, Switzerland<br/>Telephone: <a href="tel:+413138877">+41 (0)31 388 77</a></address></section>

    <section><h2>16. Protection of Intellectual Property</h2><p>inlingua is the sole owner of its teaching materials, methods, course content, trademarks, and other intellectual property, except where expressly stated otherwise. Access to or use of the Online Learning Services does not transfer any ownership, license, or other proprietary right to the User beyond the limited, personal right to use the services in accordance with these Terms.</p><p>The User may not record, reproduce, publish, distribute, transmit, sell, or otherwise make available any Online Learning Session or related material without inlingua’s prior written authorization.</p></section>

    <section><h2>17. Law and Jurisdiction</h2><p>These Terms and any dispute arising from or relating to the Online Learning Services are governed by Swiss law, without regard to conflict-of-law principles. The courts of Berne, Switzerland, have exclusive jurisdiction, subject to any mandatory consumer-protection or jurisdictional rights that cannot lawfully be excluded.</p></section>
  </article>
</main><Footer/></>}
