import Link from "next/link";
import {Mail,Phone} from "lucide-react";
import {cardDescription,outcomeDescription} from "./content-copy";
import {RelevantIcon} from "./relevant-icon";
import type {Page} from "./content";

const navigation=<><Link href="/">Home</Link><Link href="/services">Services</Link><Link href="/industries">Industries</Link><Link href="/language-education">Education</Link><Link href="/government-contracting">Government</Link><Link href="/blog">Blog</Link></>;
const placementTest=<a className="button compact placement-test" href="https://my.inlingua.com/placementtest/adaptive/" target="_blank" rel="noopener noreferrer">Inlingua placement test <span aria-hidden="true">↗</span></a>;
export function Header(){return <><a className="skip" href="#main">Skip to content</a><div className="utility-bar"><div className="shell"><div className="utility-contact"><a className="utility-email" href="mailto:contact@inlinguabostonma.com"><Mail aria-hidden="true"/> <span>contact@inlinguabostonma.com</span></a><a className="utility-phone" href="tel:+16175465590"><Phone aria-hidden="true"/> <span>617-546-5590</span></a></div><div className="utility-actions">{placementTest}<Link className="button compact utility-quote" href="/request-a-quote">Request quote</Link></div></div></div><header className="nav shell"><Link href="/" className="brand brand-logo" aria-label="inlingua Boston home"><img src="/images/inlingua-boston-logo.png" width="141" height="78" alt="inlingua Boston"/></Link><nav aria-label="Primary navigation">{navigation}</nav><div className="header-actions"><Link className="button compact" href="/request-a-quote">Request a quote</Link></div><details className="mobile-menu"><summary aria-label="Open navigation menu"><span/><span/><span/></summary><div className="mobile-menu-panel"><nav aria-label="Mobile navigation">{navigation}</nav></div></details></header></>}
export function HeroImage({src,alt,priority=false}:{src:string;alt:string;priority?:boolean}){return <figure className="hero-image"><img src={src} alt={alt} width="1729" height="909" loading={priority?"eager":"lazy"} fetchPriority={priority?"high":"auto"}/><span aria-hidden="true"/></figure>}
export function Footer(){return <footer><div className="shell footer-grid"><div><Link href="/" className="brand brand-logo footer-logo" aria-label="inlingua Boston home"><img src="/images/inlingua-boston-logo.png" width="141" height="78" alt="inlingua Boston"/></Link><p>The Language School of Boston and a partner for professional language services—designed around the people who need to understand one another.</p></div><div><b>Solutions</b><Link href="/services/interpretation">Interpretation</Link><Link href="/services/translation">Translation</Link><Link href="/services/transcription">Transcription</Link><Link href="/corporate-language-solutions">Organizations</Link></div><div><b>Learn</b><Link href="/language-education">Language education</Link><Link href="/resources">Resources</Link><Link href="/about">About</Link></div><div><b>Start here</b><Link href="/request-a-quote">Request a quote</Link><Link href="/contact">Contact</Link><Link href="/government-contracting">Procurement</Link></div></div><div className="shell legal">© 2026 inlingua Boston <span>Privacy · Accessibility · Terms</span></div></footer>}
export function JsonLd({page}:{page:Page}){const data={"@context":"https://schema.org","@type":"Service",name:page.title,description:page.description,provider:{"@type":"Organization",name:"inlingua Boston"},areaServed:[{"@type":"AdministrativeArea",name:"Greater Boston"},{"@type":"Country",name:"United States"}]};return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/>}
export function DetailPage({page}:{page:Page}){const image=page.slug.startsWith("government")?"/images/hero-government.jpg":page.slug.startsWith("language")||page.slug.startsWith("interpreter")?"/images/hero-education-training.jpg":"/images/hero-professional-services.jpg";return <><JsonLd page={page}/><Header/><main id="main"><section className="page-hero visual-hero"><div className="shell"><div><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p><div className="actions"><Link className="button lime" href="/request-a-quote">{page.cta} <span>→</span></Link><Link className="text-link light-link" href="/contact">Talk with a specialist ↗</Link></div></div><HeroImage src={image} alt={`${page.title} — professional multilingual communication and language access`}/></div></section><section className="section shell"><div className="section-head"><p>HOW WE CAN HELP</p><h2>Built around the setting, audience, and outcome.</h2></div><div className="tile-grid">{page.services.map((x,i)=><article className="tile" key={x}><RelevantIcon label={x}/><span>0{i+1}</span><h3>{x}</h3><p>{cardDescription(page,x,i)}</p></article>)}</div></section><section className="dark-section"><div className="shell split"><div><p className="eyebrow lime-text">A clearer path</p><h2>Turn priorities into a practical next step.</h2></div><ol>{page.outcomes.map((x,i)=><li key={x}><span>{i+1}</span><div><b>{x}</b><p>{outcomeDescription(page,x,i)}</p></div></li>)}</ol></div></section><section className="section shell faq"><div><p className="eyebrow">Common questions</p><h2>Before you get started.</h2></div><div>{page.faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section><Cta/></main><Footer/></>}
export function Cta(){return <section className="cta"><div className="shell"><p>READY WHEN YOU ARE</p><h2>What language service do you need today?</h2><div><Link className="button lime" href="/request-a-quote">Request a quote <span>→</span></Link><Link href="/contact">Ask a question ↗</Link></div></div></section>}
