import type {Page} from "./content";import type {Subservice} from "./subservices";

const explanations:Record<string,string>={
 "Interpretation":"Coordinate spoken or signed communication around the participants, setting, and delivery mode.","Translation":"Turn source documents into reader-ready content for a defined language, audience, and use.","Transcription & captions":"Convert recorded speech into usable text, captions, or subtitle-ready material.","Localization":"Adapt content and digital experiences for local language, culture, and user expectations.","Language assessments":"Understand current ability before making placement, training, or workforce decisions.","Corporate training":"Build role-relevant communication skills around the work employees actually perform.",
 "Healthcare":"Support patient, family, workforce, and community communication across care settings.","Government":"Make public information, meetings, programs, and services more accessible across languages.","Legal":"Plan language support around proceedings, participants, documents, and venue requirements.","Education":"Connect students, families, educators, and institutions through multilingual communication.","Utilities":"Clarify customer, safety, field, and emergency communication for essential services.","Corporate & workforce":"Develop scalable language access and practical communication skills across an organization.",
 "Spanish":"Explore Spanish services for conversations, documents, recorded content, and learning goals.","Portuguese":"Plan Portuguese language support around the audience, regional context, and intended outcome.","Cape Verdean Creole":"Connect Cape Verdean Creole speakers with suitable interpretation and translated information.","Haitian Creole":"Support Haitian Creole communication across community, public-service, and organizational settings.","Arabic":"Confirm Arabic variety, subject matter, and format before matching the language solution.","Mandarin":"Coordinate Mandarin support for spoken interactions, written content, media, and education.",
 "Our story":"Understand how the organization’s education and language-service work has evolved in Boston.","Leadership":"Introduce the people responsible for strategy, service quality, and organizational direction.","Quality approach":"Explain how scope, language fit, subject matter, review, and feedback shape delivery.","Community involvement":"Show how language work connects with the communities and institutions it serves.","Global network":"Describe the verified relationship with the wider inlingua network and its practical value.","Technology":"Explain where tools support—not replace—professional language judgment.",
 "Interpreter request checklist":"Gather languages, participants, format, setting, timing, and access needs before booking.","Translation preparation guide":"Prepare complete, legible source files and document the recipient’s requirements.","Conference planning guide":"Align sessions, languages, technology, speakers, and attendee instructions early.","Language access guide":"Create a consistent route for people to identify and receive appropriate language support.","Procurement resources":"Give buyers a verified path to capabilities, vendor information, and onboarding documents.","Case studies":"Use approved examples to show the problem, approach, constraints, and measurable result."
};

export function cardDescription(page:Page,item:string,index:number){if(explanations[item])return explanations[item];if(page.slug.startsWith("languages/")){const language=page.title.replace(" language services","");if(item.includes("interpretation"))return `Plan ${language} support for live conversations, meetings, appointments, or events.`;if(item.includes("translation"))return `Translate documents and digital content into or from ${language} for a defined reader and purpose.`;if(item.includes("transcription"))return `Turn ${language} audio or video into structured text, captions, or subtitle-ready content.`;if(item.includes("training"))return `Explore ${language} learning options aligned with level, format, schedule, and real-world goals.`;if(item.includes("Industry"))return `Match ${language} professionals to the terminology and expectations of the operating environment.`;return `Compare remote and in-person ${language} options based on access, timing, and interaction needs.`}const subject=page.title.toLowerCase();const leads=[`Use ${item.toLowerCase()} to address the specific communication needs within ${subject}.`,`Shape ${item.toLowerCase()} around the audience, environment, and desired result.`,`Connect ${item.toLowerCase()} with the adjacent services required for a complete experience.`,`Define ownership, timing, and review expectations for ${item.toLowerCase()} before launch.`,`Make ${item.toLowerCase()} practical for the people who will use it day to day.`,`Evaluate ${item.toLowerCase()} against the organization’s verified requirements and priorities.`];return leads[index%leads.length]}

export function outcomeDescription(page:Page,outcome:string,index:number){const texts=[`${outcome} by defining the audience, constraints, and success criteria early.`,`${outcome} through a workflow suited to ${page.eyebrow.toLowerCase()} needs.`,`${outcome} while keeping language, subject matter, timing, and access requirements visible.`];return texts[index%texts.length]}

export function workflowDescription(item:Subservice,step:string,index:number){const deliverable=item.deliverables[index%item.deliverables.length];const audience=item.audiences[index%item.audiences.length];return `${step} with ${deliverable.toLowerCase()} and the needs of ${audience.toLowerCase()} clearly documented.`}
