export type Page = {slug:string; title:string; eyebrow:string; description:string; intro:string; services:string[]; outcomes:string[]; faq:[string,string][]; cta:string};

const faq=(topic:string):[string,string][]=>[
  [`How do I request ${topic.toLowerCase()}?`,`Tell us the languages, setting, timing, and scope. We will review the request and follow up with the right next steps.`],
  ["Which languages are available?","Availability depends on service, specialization, location, and timing. Share your requirements so the team can confirm coverage."],
  ["How is quality managed?","Projects are matched by language pair, subject matter, and delivery setting, with a defined review and feedback process."],
];
const make=(slug:string,title:string,eyebrow:string,description:string,intro:string,services:string[],outcomes:string[],cta="Request a quote"):Page=>({slug,title,eyebrow,description,intro,services,outcomes,faq:faq(title),cta});

export const pages:Page[]=[
  make("services","Professional language services","Solutions","Interpretation, translation, transcription, localization, and language assessment solutions.","Build language access around real people, real settings, and measurable communication needs.",["Interpretation","Translation","Transcription & captions","Localization","Language assessments","Corporate training"],["Reach multilingual audiences","Support equitable access","Reduce communication friction"]),
  make("services/interpretation","Interpretation that keeps every conversation moving","Interpretation","On-site, remote, simultaneous, consecutive, medical, legal, conference, and community interpretation.","From a patient visit to a public meeting, choose an interpretation format designed around the setting, participants, and stakes.",["On-site interpretation","Video remote interpretation","Telephone interpretation","Simultaneous interpretation","Consecutive interpretation","ASL interpretation"],["Plan the right delivery mode","Match subject-matter needs","Prepare participants for success"],"Schedule an interpreter"),
  make("services/translation","Translation built for the document—and the reader","Translation","Professional document, website, technical, legal, medical, and corporate translation services.","Your translation should work in its destination context, not simply mirror the source word for word.",["Certified & personal documents","Legal and government documents","Medical materials","Employee handbooks","Technical manuals","Websites & marketing"],["Clarify purpose and audience","Protect formatting and meaning","Add review where the use case requires it"],"Request translation pricing"),
  make("services/transcription","Transcription, captions, and subtitles with human context","Transcription","Multilingual transcription, captioning, subtitling, and human-edited speech-to-text services.","Turn recorded conversations into useful, accessible text with a workflow suited to your content and audience.",["Medical transcription","Legal transcription","Interviews & research","Meetings & podcasts","Closed captions","Multilingual subtitles"],["Make content searchable","Improve accessibility","Prepare content for translation"]),
  make("services/localization","Localization for experiences that travel","Localization","Website, software, e-learning, and marketing localization for multilingual audiences.","Adapt language, tone, format, and user experience so content feels made for each market.",["Website localization","Software strings","E-learning","Multilingual SEO","Creative adaptation","Quality review"],["Enter markets with clarity","Keep brand voice consistent","Design for local expectations"]),
  make("services/language-assessments","Language proficiency assessments for better decisions","Assessment","Language proficiency assessments for hiring, placement, workforce development, and training.","Use a clear assessment process to understand current ability and choose the right learning or workforce path.",["Placement testing","Speaking assessment","Workforce assessment","Program benchmarking","Role-based evaluation","Progress checks"],["Place learners accurately","Identify skill gaps","Track progress over time"],"Request an assessment"),
  make("industries","Language solutions by industry","Industries","Explore language access, multilingual communication, and workforce training by industry.","The same language request can carry very different risks and expectations in a clinic, courtroom, classroom, field operation, or public meeting.",["Healthcare","Government","Legal","Education","Utilities","Corporate & workforce"],["Reflect the operating context","Choose relevant services","Build a repeatable program"]),
  make("industries/healthcare","Language access for healthcare","Healthcare","Interpretation, translation, and language training for hospitals, clinics, behavioral health, dental, and community health.","Support clearer communication across appointments, care materials, outreach, and staff development.",["Medical interpretation","Telehealth support","Patient document translation","Behavioral health settings","Community outreach","Healthcare language training"],["Improve patient understanding","Support care-team communication","Build repeatable access workflows"]),
  make("industries/government","Language solutions for public service","Government","Interpretation, translation, training, and multilingual outreach for agencies and municipalities.","Help residents access public information, meetings, programs, and essential services across languages.",["Public meeting interpretation","Document translation","Community outreach","Emergency communications","Workforce language training","Language access planning"],["Reach more residents","Improve program access","Plan procurement-ready engagements"]),
  make("industries/legal","Language support for legal settings","Legal","Court, deposition, attorney meeting, document translation, and legal transcription support.","Coordinate language support around the proceeding, participants, document type, and required delivery format.",["Court interpretation","Depositions","Attorney-client meetings","Legal document translation","Hearing transcription","Remote interpretation"],["Prepare the setting","Match legal context","Keep delivery organized"]),
  make("industries/education","Language access for schools and universities","Education","Interpretation, translation, language education, and multilingual family engagement.","Connect students, families, educators, and administrators through coordinated language services.",["Family meeting interpretation","Student document translation","Campus language programs","International student English","Staff training","Multilingual outreach"],["Engage multilingual families","Support international learners","Build staff capability"]),
  make("industries/utilities","Language access for utilities and essential services","Utilities","Multilingual customer communication, field interpretation, document translation, and workforce training.","Make essential information understandable across customer service, field operations, safety, and community engagement.",["Customer interpretation","Safety material translation","Emergency messaging","Field communication","Workforce English","Community meetings"],["Improve customer access","Support safer communication","Standardize multilingual materials"]),
  make("industries/manufacturing","Language solutions for manufacturing teams","Manufacturing","Workforce English, safety communication, interpretation, and translation for manufacturers.","Help multilingual teams understand procedures, training, safety information, and operational change.",["Safety training translation","Workforce English","On-site interpretation","Technical manuals","Supervisor communication","New-hire support"],["Reinforce safer operations","Accelerate onboarding","Strengthen team communication"]),
  make("industries/technology","Language solutions for technology organizations","Technology","Localization, technical translation, global team training, and event interpretation.","Scale products, knowledge, and collaboration across markets without losing precision.",["Product localization","Technical documentation","Global team training","Conference interpretation","E-learning localization","Multilingual research"],["Support product expansion","Align distributed teams","Communicate technical ideas clearly"]),
  make("industries/finance","Language access for financial services","Finance","Translation, interpretation, and staff language training for financial institutions.","Support multilingual customers and teams across complex, high-trust communications.",["Customer interpretation","Financial document translation","Staff language training","Community outreach","Meeting support","Digital content localization"],["Improve customer understanding","Support consistent messaging","Expand multilingual access"]),
  make("industries/construction","Language solutions for construction and field teams","Construction","Safety translation, workforce English, and interpretation for job sites and construction firms.","Make safety, training, and coordination clearer for multilingual field teams.",["Toolbox talk interpretation","Safety material translation","Workforce English","Supervisor coaching","Onboarding support","Incident communication"],["Support job-site safety","Improve crew coordination","Build practical language skills"]),
  make("industries/insurance","Language access for insurance organizations","Insurance","Interpretation, translation, and multilingual customer support for insurance workflows.","Help customers navigate conversations and documents at important moments.",["Claims interpretation","Policy translation","Customer service support","Meeting interpretation","Form translation","Staff training"],["Improve customer clarity","Support consistent service","Reduce avoidable friction"]),
  make("industries/hospitality","Language training for hospitality teams","Hospitality","Workforce language training, translation, and interpretation for hospitality organizations.","Give guest-facing and operational teams practical language skills for better service.",["Guest service English","Manager coaching","Multilingual materials","Onboarding support","Interpretation","Role-based training"],["Improve guest experience","Build staff confidence","Standardize service language"]),
  make("corporate-language-solutions","Language access solutions for organizations","Organizations","Interpretation, translation, assessments, and training coordinated through one partner.","Create a practical language program around your customers, workforce, compliance needs, and growth plans.",["Managed interpretation","Translation programs","Corporate language training","Workforce assessments","Localization","Program reporting"],["Centralize language needs","Build a scalable program","Equip multilingual teams"],"Schedule a consultation"),
  make("government-contracting","Government contracting & procurement","Procurement","Procurement information and language service capabilities for public-sector buyers.","A clear starting point for agency buyers, vendor onboarding teams, and procurement partners.",["Capability overview","Service categories","Coverage planning","Vendor onboarding","Insurance documentation","Procurement contact"],["Simplify vendor review","Align scope and requirements","Coordinate next steps"],"Contact procurement"),
  make("government-contracting/capability-statement","Capability statement","Procurement resource","A concise overview of inlingua Boston language service capabilities for public-sector buyers.","Use this page as a web-based capability overview. Downloadable statements and identifiers will be added after client verification.",["Core competencies","Differentiators","Service delivery","Industry experience","Coverage model","Contact information"],["Review capabilities quickly","Plan a sourcing conversation","Request verified documents"],"Request procurement documents"),
  make("government-contracting/vendor-information","Vendor information","Procurement resource","A verification-first vendor information page for public procurement teams.","Company identifiers, registrations, insurance documents, and payment forms will appear here only after review and approval.",["Vendor profile","Registration status","Insurance documentation","W-9 request","Accessibility information","Procurement contact"],["Find current documents","Reduce onboarding friction","Confirm official details"],"Request vendor information"),
  make("language-education","Language education for real-world progress","Education","English and foreign-language programs for individuals, professionals, and organizations.","Choose a learning format aligned to your level, goals, schedule, and real communication needs.",["General English","Business English","Private lessons","Group programs","Foreign languages","Online learning"],["Build practical confidence","Learn with clear goals","Track meaningful progress"],"Find your program"),
  make("language-education/english","English programs for life, study, and work","English programs","General, intensive, private, and professional English programs in Boston and online.","Build the English skills you need for daily life, academic goals, or professional growth.",["General English","Private English","Business English","Conversation practice","Online English","Placement assessment"],["Improve fluency","Build confidence","Use English in real situations"],"Book a placement test"),
  make("language-education/english/general-english","General English","English program","General English instruction in Greater Boston with integrated speaking, listening, reading, writing, grammar, vocabulary, and pronunciation.","Build balanced English skills through communication-first, instructor-led learning.",["Communication in context","Integrated skills","Guided practice","Applied conversation","Instructor feedback","Progress review"],["Build a broad foundation","Use English more confidently","Connect accuracy with communication"],"Ask about General English"),
  make("language-education/english/intensive-english","Intensive English","English program","Intensive English study in Greater Boston for learners seeking frequent instruction and a concentrated learning rhythm.","Build momentum through higher-frequency English study and deliberate practice.",["Frequent instruction","Skills workshops","Applied tasks","Vocabulary development","Writing practice","Progress review"],["Accelerate development","Strengthen learning habits","Practice English consistently"],"Ask about Intensive English"),
  make("language-education/english/private-classes","Private Classes","English program","Personalized private English classes shaped around individual goals, schedules, communication situations, and current ability.","Use one-to-one lesson time for the English skills and situations that matter most.",["Needs analysis","Personalized input","Scenario practice","Pronunciation coaching","Professional communication","Focused feedback"],["Address specific goals","Learn at an appropriate pace","Receive individual feedback"],"Discuss private classes"),
  make("language-education/english/semi-intensive-english","Semi-Intensive English","English program","Semi-intensive English classes combining consistent instruction with a balanced recurring schedule.","Build steady progress through integrated skills, communication practice, and instructor feedback.",["Recurring instruction","Integrated skills","Applied conversation","Grammar and vocabulary","Independent practice","Progress review"],["Build steady momentum","Balance study with other commitments","Practice consistently"],"Ask about Semi-Intensive English"),
  make("language-education/english/business-english","Business English","Professional English","Business English training for meetings, email, presentations, customer communication, collaboration, and role-specific workplace language.","Develop professional English through realistic workplace tasks and communication practice.",["Meetings","Professional email","Presentations","Customer communication","Role-specific vocabulary","Cross-cultural communication"],["Communicate more clearly at work","Practice professional tasks","Build role-relevant language"],"Discuss Business English"),
  make("language-education/english/english-brushup","English BrushUp","English refresher","English refresher classes for learners reactivating grammar, vocabulary, fluency, listening, pronunciation, and communication confidence.","Refresh existing knowledge through purposeful review and active use.",["Grammar refresh","Vocabulary activation","Speaking confidence","Listening and response","Pronunciation","Applied practice"],["Reactivate existing knowledge","Communicate more confidently","Prepare for renewed English use"],"Ask about English BrushUp"),
  make("language-education/english/online-offsite","On-line & Off-site English","Flexible English","Live English instruction delivered online or at an approved off-site location with interactive lessons and instructor feedback.","Choose a flexible delivery route while keeping learning active and structured.",["Live instruction","Online delivery","Off-site coordination","Shared materials","Independent practice","Instructor feedback"],["Learn flexibly","Stay actively involved","Connect lessons with real communication"],"Ask about online or off-site English"),
  make("language-education/inlingua-boston","inlingua Boston Language Education","School overview","Explore the school, method, student services, staff, learning formats, and the Greater Boston learning environment.","Understand the school and support surrounding your language program.",["School information","Teaching method","Student services","Administrative staff","Boston information","Program pathways"],["Know the school","Choose a learning path","Prepare for enrollment"]),
  make("language-education/foreign-languages","Foreign Language Classes","Foreign languages","Private and group foreign-language instruction shaped around level, goals, schedule, and current availability.","Choose individual focus or group interaction for the language you want to learn.",["Private classes","Group classes","Placement","Instructor-led learning","Online or in person","Program planning"],["Choose a format","Build communication skills","Confirm current availability"]),
  make("language-education/foreign-languages/private","Private Foreign-Language Classes","Foreign languages","One-to-one foreign-language instruction shaped around the learner's level, goals, pace, and schedule.","Build a personalized foreign-language learning plan.",["Needs analysis","Private instruction","Flexible pacing","Practical communication","Instructor feedback","Program planning"],["Focus on individual goals","Learn at a suitable pace","Confirm a workable schedule"]),
  make("language-education/foreign-languages/group","Group Foreign-Language Classes","Foreign languages","Instructor-led group foreign-language classes built around interaction, guided practice, and a suitable shared level.","Learn through structured practice and communication with a cohort.",["Group instruction","Level matching","Conversation practice","Collaborative activities","Instructor feedback","Program planning"],["Learn with others","Practice interaction","Build steady progress"]),
  make("language-education/admissions","Language School Admissions","Admissions","Admissions application guidance and current program pricing information for prospective language students.","Review what to prepare before applying or paying for a program.",["Application pathway","Program selection","Placement","Pricing information","Enrollment terms","Student inquiry"],["Prepare application details","Review current costs","Understand next steps"]),
  make("language-education/admissions/application","Admissions Application","Admissions","Application guidance for prospective inlingua Boston language students.","Prepare program, placement, contact, and enrollment information before submitting an official application.",["Program selection","Placement","Applicant information","Admissions Agreement","Enrollment terms","Education-team support"],["Prepare accurate information","Review terms before signing","Ask informed questions"]),
  make("language-education/admissions/pricing","Language Program Pricing List","Admissions pricing","Pricing categories and current tuition-request guidance for English and foreign-language programs.","Request the current tuition, fees, materials, schedule, and payment information for your selected program.",["English pricing","Foreign-language pricing","Private classes","Group classes","Materials and fees","Payment terms"],["Compare program categories","Confirm current tuition","Review conditions before payment"]),
  make("language-education/corporate","Corporate language training built around the work","Corporate training","Custom language training for teams, leaders, customer service, healthcare, safety, and global business.","Start with the roles, communication moments, and outcomes that matter to your organization.",["Business English","Executive coaching","Customer service English","Healthcare English","Safety & field English","Global team languages"],["Build job-specific skills","Fit learning around work","Measure progress"],"Request language training"),
  make("language-education/mission-goals-vision","Mission, Goals & Vision","School information","Learn about inlingua Boston's mission, education and language-access goals, and vision for bridging linguistic and cultural barriers.","A student-centered direction for education, language access, and cross-cultural communication.",["Mission","Education goals","Language-service goals","Customer care","Tailored solutions","Cross-cultural vision"],["Cultivate linguistic competency","Support cultural diversity","Bridge communication barriers"]),
  make("language-education/inlingua-method","The inlingua Method | Communication First","Teaching methodology","Explore the ten principles of the inlingua Method: direct immersion, communicative teaching, contextual practice, learner autonomy, and multimedia resources.","A direct, communicative method that helps learners develop language through active use.",["Target-language immersion","Clear learning goals","Contextual communication","Learner talking time","Authentic practice","Independent learning"],["Think in the target language","Communicate with confidence","Build autonomous learning skills"]),
  make("language-education/student-services","Student Services","Student support","Explore homestay, airport transportation, cultural guidance, activities, city tours, and general visa-process support.","Support options for students before arrival and during their learning experience.",["Homestay","Airport transportation","Cultural consulting","Social guidance","Activities and tours","General visa-process guidance"],["Prepare for arrival","Connect with local life","Confirm available support"]),
  make("language-education/administrative-staff","Administrative Staff","Our team","Meet the leadership and administrative team supporting inlingua Boston students and operations.","The people coordinating education, operations, communication, and outreach.",["Executive leadership","Operations","School direction","Administration","Student communication","Marketing"],["Know who supports the school","Reach the right team","Understand key roles"]),
  make("language-education/careers-opportunities","Careers & Opportunities","Join the team","Explore interpreter, translator, teacher, and multilingual professional opportunities at inlingua Boston.","Bring language expertise, cultural sensitivity, and professional care to the team.",["Interpreters","Translators","Teachers","Language professionals","Résumé submission","Current openings"],["Share your experience","Present relevant credentials","Apply by email"]),
  make("language-education/student-information","Student Information & Program Inquiry","Prospective students","Review the Admissions Agreement notice and request information about language programs at inlingua Boston.","Understand the difference between a program inquiry and an enrollment application.",["Admissions notice","Program inquiry","English programs","Foreign languages","Contact details","Next steps"],["Ask informed questions","Review terms before enrolling","Reach the education team"]),
  make("language-education/about-boston","About Boston for Language Students","Boston guide","Explore Boston transportation, universities, events, landmarks, activities, and regional excursions for language students.","Connect language learning with life in Greater Boston and New England.",["Transportation","Universities","Annual events","Landmarks","Activities","Regional excursions"],["Navigate the area","Discover local culture","Learn beyond the classroom"]),
  make("language-education/about-us","About inlingua Boston | School History","About the school","Read the supplied history of inlingua International and the Boston language school, subject to client verification.","A Boston school connected to an international language-learning tradition.",["International history","Boston history","Teaching tradition","Learning materials","Instructor approach","Global network"],["Understand the background","Explore the teaching tradition","Verify historical claims"]),
  make("interpreter-training","Train for the moments that require accuracy and judgment","Interpreter education","Medical, legal, professional, and advanced interpreter education programs.","Develop language-access skills through structured learning, ethical practice, terminology, and applied scenarios.",["Medical interpreter program","Legal interpreter program","Professional interpreter program","Advanced interpreter studies","Continuing education","ASL learning pathways"],["Practice interpreting techniques","Understand professional ethics","Prepare for real settings"],"Explore programs"),
  make("interpreter-training/medical","Medical interpreter training","Professional education","Medical interpreter education covering ethics, roles, terminology, and applied practice.","Build a foundation for interpreting in healthcare settings through structured instruction and practice.",["Interpreter role & boundaries","Medical terminology","Ethics & confidentiality","Modes of interpretation","Culture & communication","Applied scenarios"],["Learn healthcare context","Practice core techniques","Develop professional judgment"],"Ask about the next cohort"),
  make("interpreter-training/legal","Legal interpreter training","Professional education","Legal interpreter education covering courtroom context, ethics, terminology, and interpreting modes.","Develop an understanding of legal settings and the professional decisions interpreters face within them.",["Legal terminology","Courtroom context","Ethics & protocol","Consecutive interpreting","Simultaneous interpreting","Sight translation"],["Understand legal settings","Practice key modes","Build ethical awareness"],"Ask about the next cohort"),
  make("interpreter-training/professional","Professional interpreter education","Professional education","Comprehensive interpreter education focused on skills, ethics, terminology, and applied practice.","Move beyond bilingual ability with structured development across interpreting modes and professional settings.",["Core interpreting skills","Ethical decision-making","Terminology development","Memory & note-taking","Sight translation","Applied practice"],["Strengthen core techniques","Build professional judgment","Practice across contexts"],"Request program details"),
  make("interpreter-training/advanced","Advanced interpreter studies","Professional education","Advanced interpreter learning for experienced practitioners seeking deeper practice.","Continue developing accuracy, decision-making, specialization, and reflective professional practice.",["Advanced consecutive","Advanced simultaneous","Specialized terminology","Performance feedback","Professional practice","Continuing education"],["Refine performance","Deepen specialization","Learn through feedback"],"Request program details"),
  make("about","A Boston language institution, evolving with every community","About","Learn about inlingua Boston’s approach to language education and professional language solutions.","Our work connects individuals and organizations through learning, interpretation, translation, and professional education.",["Our story","Leadership","Quality approach","Community involvement","Global network","Technology"],["People-centered service","Practical language access","Continuous improvement"],"Talk with our team"),
  make("resources","Language access resources","Resource center","Guides, checklists, insights, and procurement resources for language access planning.","Use these resources to plan an interpreter request, prepare a translation, or shape an organization-wide language program.",["Interpreter request checklist","Translation preparation guide","Conference planning guide","Language access guide","Procurement resources","Case studies"],["Plan a clearer request","Reduce project delays","Share guidance with your team"]),
  make("blog","Language access insights","Insights","Practical articles about interpretation, translation, language education, multilingual communication, and professional practice.","Clear guidance for people planning language services, building programs, or developing professional skills.",["Choosing an interpreter","Preparing documents","Conference planning","Language access","Interpreter ethics","Human and AI workflows"],["Make informed decisions","Prepare stronger requests","Share useful guidance"]),
  make("contact","Let’s make the next conversation clearer","Contact","Contact inlingua Boston about language services, language education, organizational programs, or procurement.","Choose the path that best matches your goal and the team will route your message.",["Language services","Language programs","Corporate programs","Government procurement","General questions","Location and hours"],["Reach the right team","Share essential details","Get a clear next step"],"Send an inquiry"),
];

const languages=["Spanish","Portuguese","Brazilian Portuguese","Cape Verdean Creole","Haitian Creole","French","Arabic","Mandarin","Cantonese","Vietnamese","Russian","Ukrainian","Somali","Hindi","Urdu","Italian","German","Japanese","Korean"];
export const languagePages=languages.map(name=>make(`languages/${name.toLowerCase().replace(/ /g,"-")}`,`${name} language services`,"Language directory",`${name} interpretation, translation, transcription, and learning options in Greater Boston and beyond.`,`Explore ${name} support by service and setting. Availability and qualifications are confirmed for each request.`,[`${name} interpretation`,`${name} translation`,`${name} transcription`,`${name} language training`,"Industry-specific support","Remote and on-site options"],["Find the right service","Confirm specialist availability","Coordinate one multilingual partner"]));
export const languageIndex=make("languages","Language directory","Languages","Explore language services and learning options by language.","Start with the language, then choose the setting and support you need. Every request is confirmed for current availability and specialist fit.",["Spanish","Portuguese","Cape Verdean Creole","Haitian Creole","Arabic","Mandarin"],["Search by language","Confirm service availability","Match the setting and subject"]);
import {subservices} from "./subservices";
const subservicePages:Page[]=subservices.map(s=>({slug:s.slug,title:s.title,eyebrow:s.eyebrow,description:s.description,intro:s.problem,services:s.deliverables,outcomes:s.steps,faq:s.questions,cta:"Start a request"}));
export const allPages=[...pages,languageIndex,...languagePages,...subservicePages];
export const getPage=(slug:string)=>allPages.find(p=>p.slug===slug);
