import Link from "next/link";
import {Header,Footer,Cta} from "./components";
import {PricingCalculator} from "./pricing-calculator";

const foreignCards=[
  ["Private","One-to-one foreign-language instruction shaped around your level, schedule, goals, and preferred pace.","/language-education/foreign-languages/private"],
  ["Group","Instructor-led foreign-language classes that build communication through guided practice and interaction.","/language-education/foreign-languages/group"],
];
const admissionCards=[
  ["Admissions Application","Understand the application path, information to prepare, and steps before enrollment.","/language-education/admissions/application"],
  ["Pricing List","Review program pricing categories and request the current tuition and fee schedule.","/language-education/admissions/pricing"],
];

function Directory({type}:{type:"foreign"|"admissions"}){const foreign=type==="foreign";const cards=foreign?foreignCards:admissionCards;return <><Header/><main id="main" className="education-subdirectory"><section className={`education-path-hero ${foreign?"foreign-path-hero":"admissions-path-hero"}`}><div className="shell"><p className="eyebrow">LANGUAGE EDUCATION · {foreign?"FOREIGN LANGUAGES":"ADMISSIONS"}</p><h1>{foreign?"Choose how you want to learn a foreign language.":"Prepare for the next enrollment step."}</h1><p>{foreign?"Compare private and group formats, then confirm the language, level, schedule, tuition, and current availability.":"Start with the application process or review the program categories included in the current pricing schedule."}</p><Link href="/language-education">← Back to Language Education</Link></div></section><section className="education-choice-grid shell"><header><p>CHOOSE A PATH</p><h2>{foreign?"Private focus or group interaction.":"Application details and pricing information."}</h2></header><div>{cards.map(([title,text,href],index)=><Link href={href} key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p><b>View details →</b></Link>)}</div></section><Cta/></main><Footer/></>}

export function ForeignLanguagesPage(){return <Directory type="foreign"/>}
export function AdmissionsPage(){return <Directory type="admissions"/>}

const detailContent={
  "foreign-private":{eyebrow:"FOREIGN LANGUAGES · PRIVATE",title:"Private foreign-language classes built around one learner.",lead:"Focus your lesson time on the language, situations, pace, and schedule that matter to you.",sections:[["A personalized starting point","The education team confirms the language, current ability, learning history, goals, preferred schedule, and delivery format before recommending a plan."],["How private learning works","An instructor can adjust examples, practice, pacing, correction, and between-session work around the learner’s progress and communication priorities."],["What to confirm","Language and level, instructor availability, online or in-person format, session length, course package, tuition, materials, and cancellation terms are confirmed before enrollment."]],cta:"Ask about private classes"},
  "foreign-group":{eyebrow:"FOREIGN LANGUAGES · GROUP",title:"Group foreign-language classes designed for active participation.",lead:"Learn through instructor guidance, structured practice, and interaction with other learners at a suitable level.",sections:[["The group experience","Group learning creates opportunities to listen, respond, collaborate, role-play, and apply language with different speakers."],["Placement and cohort fit","A useful group depends on language, level, schedule, group size, learning goals, and current enrollment. Availability is confirmed before registration."],["What to confirm","Ask about the target language, start date, meeting schedule, delivery format, expected level, tuition, course materials, and minimum enrollment requirements."]],cta:"Ask about group classes"},
  "admissions-application":{eyebrow:"ADMISSIONS · APPLICATION",title:"Prepare your admissions application with clear information.",lead:"Review the program, tuition, schedule, policies, and required information before submitting an enrollment application.",sections:[["Before you apply","Choose the program or language, discuss placement, confirm the learning format and schedule, and request the current admissions materials."],["Information to prepare","Applicants may be asked for contact information, country, language of study, program selection, learning goals, and other information relevant to enrollment."],["Important agreement notice","Submitting an official enrollment application may create a binding Admissions Agreement. Review tuition, refund rules, attendance expectations, student responsibilities, and all program terms before signing or paying."]],cta:"Request admissions information"},
  "admissions-pricing":{eyebrow:"ADMISSIONS · PRICING",title:"Request the current tuition and program pricing list.",lead:"Pricing depends on the selected program, format, schedule, course length, materials, and current availability.",sections:[["English programs","Request current pricing for General English, Intensive or Semi-Intensive English, private classes, Business English, English BrushUp, and online or off-site formats."],["Foreign languages","Request current private and group pricing for the language, level, schedule, and delivery format you need."],["Before payment","Confirm tuition, registration or material fees, course dates, cancellation and refund rules, payment schedule, and any program-specific conditions in writing."]],cta:"Request the pricing list"},
} as const;

export type EducationDetailKey=keyof typeof detailContent;
export function EducationPathDetailPage({page}:{page:EducationDetailKey}){const data=detailContent[page];const pricing=page==="admissions-pricing";return <><Header/><main id="main" className="education-path-detail"><section className="education-detail-hero"><div className="shell"><p className="eyebrow">{data.eyebrow}</p><h1>{pricing?"Find the right program and estimate your tuition.":data.title}</h1><p>{pricing?"Use the calculator below to compare the English program schedules and standard or private prices included in the supplied pricing list.":data.lead}</p><div className="actions"><Link className="button" href={pricing?"#pricing-calculator-title":"/contact"}>{pricing?"Calculate pricing":data.cta} <span>→</span></Link><Link href="/language-education">Language Education ↗</Link></div></div></section>{pricing?<PricingCalculator/>:<section className="education-detail-sections shell">{data.sections.map(([title,text],index)=><article key={title}><span>0{index+1}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}</section>}<Cta/></main><Footer/></>}
