import Link from "next/link";
import {Header,Footer,Cta} from "./components";

const programs=[["English programs","Build practical English for daily life, study, and work.","/language-education/english"],["Private instruction","A focused learning plan shaped around your level, schedule, and goals.","/language-education/english/private-english"],["Foreign languages","Develop communication skills for travel, relationships, and professional life.","/languages"],["Corporate training","Role-based language development for teams and leaders.","/language-education/corporate"]];

const informationCards=[
  ["Mission, Goals & Vision","Learn how inlingua Boston approaches language access, education, cross-cultural communication, and community participation.","/about"],
  ["The inlingua Method","Explore the communication-first teaching cycle used to introduce, practice, apply, and reinforce language.","#inlingua-method"],
  ["Student Services","Ask about the student support currently available for your selected program and learning format.","/contact"],
  ["Administrative Staff","Meet the roles responsible for education guidance, program coordination, and student communication.","/about"],
  ["Careers","Explore opportunities to contribute to language education and multilingual communication at inlingua Boston.","/contact"],
  ["Opportunities","Connect with the team about teaching, partnerships, organizational programs, and community collaboration.","/contact"],
  ["Student Information","Find practical guidance for placement, program selection, enrollment conversations, and preparing to learn.","/resources"],
  ["About Boston","Discover the Greater Boston setting and the diverse communities that make it a valuable place to learn languages.","#about-boston"],
  ["Location","Find inlingua Boston at 36 Baker Road in Everett, Massachusetts, minutes from Boston.","/contact"],
  ["About Us","Learn about Language School of Boston, Inc., doing business as inlingua Boston, and the work we support.","/about"],
];

export function LanguageEducationPage(){return <><Header/><main id="main" className="education-page"><section className="education-hero"><div className="shell"><p className="eyebrow">LANGUAGE EDUCATION</p><h1>Learn for the life you want to participate in.</h1><p>Choose a program around your current level, real communication goals, preferred learning format, and schedule.</p><div><Link className="button" href="/language-education/english">Explore English programs <span>→</span></Link><a href="https://my.inlingua.com/placementtest/adaptive/" target="_blank" rel="noopener noreferrer">Take the placement test ↗</a></div></div></section>
<section className="education-information"><div className="shell"><header><p>01 · SCHOOL INFORMATION</p><h2>Know the school, the method, and the support around your program.</h2></header><div className="education-info-grid">{informationCards.map(([title,text,href],index)=><Link href={href} key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p><b>Learn more <i aria-hidden="true">→</i></b></Link>)}</div></div></section>
<section className="education-programs shell"><header><span>02</span><div><p>PROGRAM PATHS</p><h2>Different goals need different classrooms.</h2></div></header><div className="program-list">{programs.map(([title,text,href],index)=><Link href={href} key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p><b>Explore →</b></Link>)}</div></section>
<section id="inlingua-method" className="inlingua-method"><div className="shell"><div><p className="eyebrow">03 · THE INLINGUA METHOD</p><h2>Communication comes first.</h2><p>Teaching connects new language to meaningful situations, guided practice, active use, and instructor feedback. The goal is not only to recognize English or another language, but to use it more confidently when real communication is required.</p></div><ol><li><span>01</span><div><h3>Present in context</h3><p>Meet vocabulary and language patterns through a situation, conversation, visual, text, or practical goal.</p></div></li><li><span>02</span><div><h3>Practice deliberately</h3><p>Build accuracy through instructor modeling, questions, repetition, and focused activities.</p></div></li><li><span>03</span><div><h3>Use the language</h3><p>Apply learning through interaction, discussion, role-play, problem-solving, and relevant tasks.</p></div></li><li><span>04</span><div><h3>Receive feedback</h3><p>Notice progress, correct misunderstandings, and identify the next skill to strengthen.</p></div></li></ol></div></section>
<section className="learning-format"><div className="shell"><div><p className="eyebrow">04 · HOW YOU CAN LEARN</p><h2>Build the format around your week.</h2></div><div className="format-stack"><article><b>01</b><h3>Instructor-led</h3><p>Structured sessions with live feedback, guided practice, and clear progression.</p></article><article><b>02</b><h3>Private or group</h3><p>Choose individual focus or learn through conversation with a cohort.</p></article><article><b>03</b><h3>Online or in person</h3><p>Program availability and schedules are confirmed before enrollment.</p></article></div></div></section>
<section id="about-boston" className="about-boston"><div className="shell"><div><p className="eyebrow">05 · ABOUT BOSTON</p><h2>Learn in Greater Boston.</h2></div><p>Greater Boston brings together universities, healthcare organizations, public institutions, international businesses, neighborhoods, and multilingual communities. inlingua Boston is located in Everett, Massachusetts, with access to the wider Boston area.</p><Link className="button" href="/contact">View location and hours <span>→</span></Link></div></section>
<section className="education-journey shell"><p>YOUR LEARNING JOURNEY</p><div>{["Share your goals","Understand your level","Choose the program","Practice and progress"].map((step,index)=><article key={step}><span>{index+1}</span><h3>{step}</h3></article>)}</div><small>Schedules, tuition, course length, learning format, and outcomes are confirmed for the selected program.</small></section><Cta/></main><Footer/></>}
