"use client";

import {useMemo,useState} from "react";
import Link from "next/link";

type PriceOption={label:string;admission:number;tuition:number;total:number;privateTotal:number};
type Program={name:string;options:PriceOption[]};
const admission=165;
const semiPrivate=[425,645,855,1125,1365,1605,1845,2133,2325,2565,2805,3045,3285,3525,3765,4005,4245,4485,4725,4965,5205,5445,5685,5925,6165,6405,6645,6885,7125,7365,7605,7845,8085,8325,8565,8805,9045,9285,9525,9765,10005,10245,10485,10725,10965,11205,11445,11685,11925,12165,12405,12645];
const businessPrivate=[490,815,1140,1365,1665,1965,2265,2565,2865,3165,3465,3765,4065,4365,4665,4965,5265,5565,5865,6165];
const weeklyProgram=(name:string,weeks:number,business=false):Program=>({name,options:Array.from({length:weeks},(_,index)=>{const week=index+1;const tuition=business?(week<=3?275*week:250*week):(week<=3?200*week:175*week);return {label:`${week} ${week===1?"week":"weeks"} (${week*5} lessons)`,admission,tuition,total:tuition+admission,privateTotal:(business?businessPrivate:semiPrivate)[index]};})});
const programs:Program[]=[weeklyProgram("English Semi-Intensive",52),{name:"English Intensive",options:[
  ["13 weeks · 1 level · paid in full · 65 lessons",2275,2440,3025],["13 weeks · 1 level · paid in installments",2665,2865,3545],["26 weeks · 2 levels · paid in full",4030,4195,5495],["26 weeks · 2 levels · paid in installments",4420,4385,6405],["39 weeks · 3 levels · paid in full",5552.5,5717,6990],["39 weeks · 3 levels · paid in installments",6235,6400,8355],["1 year · 4 levels · paid in full",6630,6795,9265],["1 year · 4 levels · paid in installments",7990,8155,10565],
].map(([label,tuition,total,privateTotal])=>({label:String(label),admission,tuition:Number(tuition),total:Number(total),privateTotal:Number(privateTotal)}))},weeklyProgram("Business English Semi-Intensive",20,true)];
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:0,maximumFractionDigits:2});

export function PricingCalculator(){const [programIndex,setProgramIndex]=useState(0);const [optionIndex,setOptionIndex]=useState(0);const [format,setFormat]=useState<"standard"|"private">("standard");const program=programs[programIndex];const option=useMemo(()=>program.options[Math.min(optionIndex,program.options.length-1)],[program,optionIndex]);const displayedTotal=format==="private"?option.privateTotal:option.total;const changeProgram=(value:string)=>{setProgramIndex(Number(value));setOptionIndex(0)};return <section className="pricing-calculator-section shell" aria-labelledby="pricing-calculator-title"><div className="pricing-calculator-intro"><p className="eyebrow">INTERACTIVE TUITION ESTIMATE</p><h2 id="pricing-calculator-title">Calculate your program price.</h2><p>Choose a program, course length, and class format to see the amount listed in the current pricing workbook.</p></div><div className="pricing-calculator"><form className="pricing-form" onSubmit={event=>event.preventDefault()}><label>Program<select value={programIndex} onChange={event=>changeProgram(event.target.value)}>{programs.map((item,index)=><option value={index} key={item.name}>{item.name}</option>)}</select></label><label>Course length<select value={optionIndex} onChange={event=>setOptionIndex(Number(event.target.value))}>{program.options.map((item,index)=><option value={index} key={item.label}>{item.label}</option>)}</select></label><fieldset><legend>Class format</legend><div className="pricing-format-options"><label><input type="radio" name="format" checked={format==="standard"} onChange={()=>setFormat("standard")}/> Standard</label><label><input type="radio" name="format" checked={format==="private"} onChange={()=>setFormat("private")}/> Private</label></div></fieldset></form><aside className="pricing-result" aria-live="polite"><p className="eyebrow">ESTIMATED PROGRAM PRICE</p><strong>{money.format(displayedTotal)}</strong><p>{program.name}<br/>{option.label}<br/>{format==="private"?"Private format":"Standard format"}</p>{format==="standard"&&<dl><div><dt>Admissions fee</dt><dd>{money.format(option.admission)}</dd></div><div><dt>Tuition fee</dt><dd>{money.format(option.tuition)}</dd></div><div><dt>Listed total</dt><dd>{money.format(option.total)}</dd></div></dl>}{format==="private"&&<p className="pricing-private-note">The workbook provides one combined private-program amount; it does not itemize the private tuition and admissions fee separately.</p>}<Link className="button" href={`/contact?program=${encodeURIComponent(program.name)}&duration=${encodeURIComponent(option.label)}&format=${format}`}>Confirm this price <span>→</span></Link></aside></div><p className="pricing-disclaimer"><b>Estimate only.</b> Pricing is reproduced from the supplied workbook and must be confirmed by inlingua Boston before enrollment or payment. Course availability, materials, policies, and payment conditions may affect the final amount.</p></section>}
