import type {Metadata} from "next";import {notFound} from "next/navigation";import {allPages,getPage} from "../content";import {DetailPage} from "../components";import {ServicePage} from "../service-pages";import {SubservicePage} from "../subservice-page";import {getSubservice,subservices} from "../subservices";
import {InterpreterTrainingPage,GovernmentContractingPage} from "../pillar-pages";
import {LanguageEducationPage} from "../language-education-page";
import {LanguageDirectoryPage} from "../language-directory";
import {ServicesDirectoryPage,IndustriesDirectoryPage} from "../directory-pages";
import {ContactPage} from "../contact-page";
import {AboutPage} from "../about-page";
import {EnglishProgramsPage,EnglishProgramDetail,getEnglishProgram,englishPrograms} from "../english-program-pages";
import {EducationInfoPage,EducationInfoKey} from "../education-info-pages";
export function generateStaticParams(){return allPages.map(p=>({slug:p.slug.split("/")}))}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params;const p=getPage(slug.join("/"));if(!p)return {};const postponed=p.slug.startsWith("interpreter-training");return {title:p.title,description:p.description,alternates:{canonical:`/${p.slug}`},robots:postponed?{index:false,follow:false}:undefined,openGraph:{title:p.title,description:p.description,type:"website"},twitter:{card:"summary",title:p.title,description:p.description}}}
export default async function Route({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const path=slug.join("/");const page=getPage(path);if(!page)notFound();if(path==="services")return <ServicesDirectoryPage/>;if(path==="industries")return <IndustriesDirectoryPage/>;if(path==="languages")return <LanguageDirectoryPage/>;if(path==="language-education")return <LanguageEducationPage/>;if(path==="language-education/english")return <EnglishProgramsPage/>;if(path.startsWith("language-education/english/")){const program=getEnglishProgram(slug.at(-1)||"");if(program)return <EnglishProgramDetail program={program} index={englishPrograms.indexOf(program)}/>;}if(path.startsWith("language-education/")&&!["language-education/corporate"].includes(path))return <EducationInfoPage page={slug.at(-1) as EducationInfoKey}/>;if(path==="interpreter-training")return <InterpreterTrainingPage/>;if(path==="government-contracting")return <GovernmentContractingPage/>;if(path==="contact")return <ContactPage/>;if(path==="about")return <AboutPage/>;const sub=getSubservice(path);if(sub)return <SubservicePage item={sub} index={subservices.indexOf(sub)}/>;if(page.slug.startsWith("services/")&&page.slug!=="services")return <ServicePage page={page}/>;return <DetailPage page={page}/>}
