import type {Metadata} from "next";
import {Header,Footer} from "../components";

export const metadata:Metadata={title:"DMCA Policy",description:"Digital Millennium Copyright Act notice-and-takedown and counter-notification policy for inlingua Language School of Boston.",alternates:{canonical:"/dmca"}};

export default function DmcaPage(){return <><Header/><main id="main" className="policy-page dmca-page">
  <header className="policy-hero"><div className="shell"><p className="eyebrow">COPYRIGHT POLICY</p><h1>Digital Millennium Copyright Act Policy</h1><p>Effective September 8, 2021</p></div></header>
  <article className="policy-content shell">
    <section><h2>Introduction</h2><p>inlingua Language School of Boston respects the intellectual-property rights of others and expects users of <a href="https://inlinguabostonma.com">https://inlinguabostonma.com</a> (the “Website”) to do the same. In accordance with the Digital Millennium Copyright Act (“DMCA”), including 17 U.S.C. § 512(c), a copyright owner or an agent authorized to act on the owner’s behalf may submit a notification of claimed infringement concerning material available through the Website.</p><p>To the extent the Website qualifies as an internet service provider under applicable law and satisfies the conditions imposed by 17 U.S.C. § 512, the Website claims the limitations on liability and safe-harbor protections available under the DMCA.</p></section>

    <section><h2>Notice of Infringement – Claim</h2><p>A valid written notification of claimed copyright infringement must include substantially all of the following:</p><ol className="legal-number-list"><li><strong>Signature.</strong> A physical or electronic signature of the copyright owner or a person authorized to act on the owner’s behalf.</li><li><strong>Identification of the copyrighted work.</strong> Identification of the copyrighted work claimed to have been infringed or, where multiple works are covered by one notice, a representative list of those works.</li><li><strong>Identification and location of the material.</strong> Identification of the material claimed to be infringing or the subject of infringing activity, together with information reasonably sufficient to permit us to locate it, preferably including the exact URL for each item.</li><li><strong>Contact information.</strong> Information reasonably sufficient to contact the complaining party, including name, postal address, email address, telephone number, and fax number, if available.</li><li><strong>Good-faith statement.</strong> A statement that the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, the owner’s agent, or the law.</li><li><strong>Accuracy and authority statement.</strong> A statement that the information in the notification is accurate and, under penalty of perjury, that the complaining party is the copyright owner or is authorized to act on the copyright owner’s behalf.</li></ol><p>Under 17 U.S.C. § 512(f), a person who knowingly materially misrepresents that material or activity is infringing may be liable for damages, including costs and attorneys’ fees incurred by the alleged infringer, copyright owner, copyright owner’s authorized licensee, or service provider as a result of relying on that misrepresentation.</p><p>Send a takedown notice through our <a href="/contact">Contact page</a>. Submission by email is preferred. A claimant’s identity and the information contained in the notice may be forwarded to the person who posted or controls the allegedly infringing material or otherwise disclosed as reasonably necessary to process the claim.</p></section>

    <section><h2>Counter Notification – Restoration of Material</h2><p>If material submitted by a user is removed or access is disabled in response to a DMCA notice, the user may submit a counter-notification under 17 U.S.C. § 512(g)(3). A valid counter-notification must include substantially all of the following:</p><ol className="legal-number-list"><li><strong>Signature.</strong> The user’s physical or electronic signature.</li><li><strong>Description and original location.</strong> Identification of the material removed or disabled and the location at which it appeared before removal or disabling.</li><li><strong>Good-faith and perjury statement.</strong> A statement under penalty of perjury that the user has a good-faith belief that the material was removed or disabled as a result of mistake or misidentification.</li><li><strong>Contact information.</strong> The user’s name, address, telephone number, and email address.</li><li><strong>Consent to jurisdiction and service.</strong> A statement consenting to the jurisdiction of the federal district court for the judicial district in which the user’s address is located—or, if the user is outside the United States, any judicial district in which the service provider may be found—and agreeing to accept service of process from the person who submitted the original notification or that person’s agent.</li></ol><p>Send a counter-notification through our <a href="/contact">Contact page</a>. Submission by email is preferred. After receiving a valid counter-notification, we may forward it to the original complaining party and restore the material in accordance with the timing and procedures established by the DMCA, unless we receive notice that the complaining party has filed an action seeking a court order to restrain the allegedly infringing activity.</p></section>

    <section><h2>Repeat Infringer Policy</h2><p>We maintain records of DMCA notifications and counter-notifications received in connection with the Website. In appropriate circumstances and at our discretion, we terminate or restrict accounts and access associated with users determined to be repeat infringers.</p></section>

    <section><h2>Modifications</h2><p>We reserve the right to modify this DMCA Policy and the procedures described on this page at any time. Any revised policy will be posted on the Website with an updated effective date. Users and copyright owners are encouraged to review this page periodically.</p></section>

    <p className="legal-generator-credit">DMCA generated by WPLP Legal Pages</p>
  </article>
</main><Footer/></>}
