import type {Metadata} from "next";
import {Header,Footer} from "../components";

export const metadata:Metadata={title:"Terms of Use",description:"Website terms and Online Learning Services policies for inlingua Language School of Boston.",alternates:{canonical:"/terms-of-use"}};

export default function TermsOfUsePage(){return <><Header/><main id="main" className="policy-page terms-page">
  <header className="policy-hero"><div className="shell"><p className="eyebrow">LEGAL NOTICE</p><h1>Terms of Use</h1><p>inlingua Language School of Boston · Effective August 26, 2026</p></div></header>
  <article className="policy-content shell">
    <header className="policy-part"><span>PART 1</span><h2>Website Terms and Conditions</h2></header>

    <section><h2>Introduction</h2><p>These terms and conditions govern the use of this website (the “Website”) by each visitor or user (the “User”). By accessing or using the Website, the User accepts these terms and conditions in full. If the User does not agree with any part of them, the User must not use the Website.</p><p>The Website may use cookies and similar technologies. Where consent is required, the User will be given an opportunity to make or manage cookie choices. Additional information about cookies and personal-information practices is available through the applicable privacy and cookies policy of inlingua International AG and the Website’s <a href="/privacy-policy">Privacy Policy</a>.</p></section>

    <section><h2>License to Use Website</h2><p>Unless otherwise stated, inlingua International AG and its licensors own the intellectual-property rights in the Website and material appearing on it. Subject to the license below, all such rights are reserved.</p><p>The User may view pages, download materials for temporary personal reference, and print pages for personal, non-commercial use, subject to these terms and any notices appearing on the relevant material. The User must not:</p><ul><li>Republish material from the Website, including republication on another website;</li><li>Sell, rent, or sub-license Website material;</li><li>Show or display Website material in public without written authorization;</li><li>Reproduce, duplicate, copy, or otherwise exploit Website material for a commercial purpose;</li><li>Edit or otherwise modify Website material; or</li><li>Redistribute Website material except where content is expressly made available for redistribution.</li></ul></section>

    <section><h2>Acceptable Use</h2><p>The User must not use the Website in any way that is unlawful, illegal, fraudulent, harmful, or connected with an unlawful, illegal, fraudulent, or harmful purpose or activity. The User must not introduce or distribute spyware, viruses, Trojan horses, worms, keystroke loggers, rootkits, malicious software, or other harmful code.</p><p>The User must not conduct systematic or automated data collection activities—including scraping, data mining, data extraction, or data harvesting—on or in relation to the Website without prior written consent. The Website must not be used to transmit unsolicited commercial communications or for marketing activities without express written authorization.</p></section>

    <section><h2>No Warranties</h2><p>The Website is provided “as is” without representations or warranties, express or implied. To the extent permitted by law, the company disclaims warranties of merchantability, fitness for a particular purpose, non-infringement, and any warranty arising from course of dealing or usage. The company does not warrant that the Website will always be available, uninterrupted, secure, error-free, or that its information will be complete, accurate, or current.</p></section>

    <section><h2>Limitations of Liability</h2><p>To the fullest extent permitted by applicable law, the company will not be liable in relation to the Website or these terms for any direct, indirect, special, incidental, punitive, or consequential loss; loss of revenue, income, profits, anticipated savings, contracts, business, goodwill, reputation, data, or information; or business interruption, whether arising in contract, tort, negligence, statute, or otherwise, even if advised of the possibility of such loss.</p></section>

    <section><h2>Exceptions</h2><p>Nothing in these terms excludes or limits liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation, or any other liability that applicable law does not permit to be excluded or limited.</p></section>

    <section><h2>Reasonableness</h2><p>By using the Website, the User agrees that the exclusions and limitations of liability stated in these terms are reasonable. If the User considers them unreasonable, the User must not use the Website.</p></section>

    <section><h2>Other Parties</h2><p>The User accepts that the limitations and protections stated in these terms protect the company’s officers, directors, employees, agents, affiliates, subsidiaries, successors, assigns, and sub-contractors, as well as the company itself.</p></section>

    <section><h2>Unenforceable Provisions</h2><p>If any disclaimer, limitation, or other provision is or becomes unenforceable under Massachusetts law, that provision will be enforced to the maximum extent permitted, and its unenforceability will not affect the enforceability of the remaining provisions.</p></section>

    <section><h2>Indemnity</h2><p>The User agrees to indemnify, defend, and hold harmless the company and its officers, employees, agents, licensors, affiliates, and successors from losses, damages, liabilities, costs, claims, and expenses, including reasonable legal fees, arising from the User’s breach of these terms or misuse of the Website, to the extent permitted by law.</p></section>

    <section><h2>Breaches of These Terms and Conditions</h2><p>Without prejudice to other rights, if the User breaches these terms, the company may suspend or prohibit access to the Website, block computers or IP addresses, contact the User’s internet service provider to request that access be blocked, and commence legal proceedings.</p></section>

    <section><h2>Variation</h2><p>The company may revise these terms from time to time. Revised terms apply from the date they are posted on the Website unless otherwise stated. The User should review this page regularly.</p></section>

    <section><h2>Assignment</h2><p>The company may transfer, sub-contract, or otherwise deal with its rights or obligations under these terms without notifying the User, subject to applicable law. The User may not transfer, sub-contract, or otherwise deal with the User’s rights or obligations without prior written consent.</p></section>

    <section><h2>Severability</h2><p>If a court or other competent authority determines that any provision is unlawful or unenforceable, the remaining provisions remain in effect. Where deletion of part of a provision would make it lawful or enforceable, that part will be deemed deleted.</p></section>

    <section><h2>Entire Agreement</h2><p>These terms, together with the Website Privacy Policy and any other policies expressly incorporated by reference, constitute the entire agreement concerning use of the Website and supersede prior understandings concerning that use.</p></section>

    <section><h2>Law and Jurisdiction</h2><p>Part 1 and all disputes relating to the Website are governed by the laws of the Commonwealth of Massachusetts, without regard to conflict-of-law principles. Subject to any mandatory rights that cannot lawfully be waived, the state and federal courts located in Massachusetts have jurisdiction over such disputes.</p></section>

    <header className="policy-part"><span>PART 2</span><h2>Policy &amp; Privacy</h2><p>Online Learning Services terms</p></header>

    <section><h2>Preamble</h2><p>For Part 2, “inlingua” means inlingua International Ltd.; “Services” means the online learning, placement, instructional, and related digital services made available by inlingua; “User” means a person who registers for, accesses, purchases, or uses the Services; and “Center” means a local inlingua language center, including inlingua Language School of Boston.</p><p>These terms govern the Services unless varied by an express written agreement. The applicable Boston Center terms apply in addition to these terms for services booked, delivered, or supported locally. If a Center term conflicts with Part 2, Part 2 takes precedence to the extent of the conflict.</p></section>

    <section><h2>Access to Services and Place of Provision of Services</h2><p>The Services are provided online. The User chooses the location from which the Services are accessed and is responsible for selecting a suitable, safe, and lawful environment. A Center may offer additional services, support, or local delivery arrangements under separate terms.</p></section>

    <section><h2>Use of Services</h2><p>The User must register or book in accordance with instructions supplied by the Website or Center. The User receives a personal login and password and is responsible for keeping them secure. Subject to availability, the Services may be accessed 24 hours a day, seven days a week.</p><p>Access may be interrupted for maintenance, updates, security work, or other operational reasons, without compensation. inlingua is not responsible for access difficulties caused by the User’s failure to meet minimum technical requirements, including compatible devices, software, internet access, audio, or video capability.</p></section>

    <section><h2>Confidentiality – Protection of Personal Privacy</h2><p>To the extent applicable, inlingua processes personal information in accordance with Regulation (EU) 2016/679 (the GDPR) and the Swiss Federal Act on Data Protection. inlingua uses reasonable technical and organizational safeguards, which may include SSL encryption, firewalls, software and vulnerability scans, access controls, and security audits.</p><p>No internet transmission or storage method is completely secure, and absolute security cannot be guaranteed. A User who identifies an unauthorized or fraudulent charge should promptly contact inlingua or the Center and the User’s payment-card provider.</p></section>

    <section><h2>Protection of Children’s Information</h2><p>The Services and Website are intended for a general audience and are not directed to children under 18. inlingua does not knowingly collect personal information from a person under 18 without permission from a parent or legal guardian.</p></section>

    <section><h2>Registration and Personal Profile</h2><p>The User must provide true, accurate, complete, and current information, must not use a false identity, and must promptly update changed information. Access credentials are personal and non-transferable.</p><p>Depending on the Service, a profile may display the User’s first and last name, username, password, email address, telephone number, gender, date of birth, country, city, province, region, interface language, time zone, and Skype ID. Profile information is visible only to authorized administrators and, where applicable, a company supervisor.</p><p>Information may be used to:</p><ul><li>Deliver, administer, personalize, and bill for Services;</li><li>Manage accounts, registration, scheduling, and customer support;</li><li>Contact the User regarding Services, transactions, and inquiries;</li><li>Conduct research and analyze usage or learning outcomes;</li><li>Maintain, secure, and improve the Website and Services;</li><li>Enforce applicable agreements and protect legal rights;</li><li>Operate and administer the business; and</li><li>Fulfill other purposes disclosed when information is collected.</li></ul></section>

    <section><h2>Access to Personal Information</h2><p>The User may amend account information through available profile controls or by contacting Customer Service or the Center. The User may request account deletion, subject to legal and record-retention requirements. Deletion does not entitle the User to a refund for undelivered or unused Services, and deleted account or learning data may not be recoverable. Information is retained while the account is active and thereafter as reasonably necessary to provide Services, comply with law, resolve disputes, and enforce agreements.</p></section>

    <section><h2>Who inlingua Shares the User’s Information With</h2><p>Information may be shared with authorized service providers supporting payment processing, hosting, customer service, technical operation, and administration; with the applicable local Center; and with assigned trainers for pedagogical purposes such as placement, progress, attendance, and test reporting.</p><p>Information may also be disclosed in response to subpoena, court order, fraud or security investigation, lawful government request, or where necessary to protect rights, property, or safety. If inlingua undergoes a merger, acquisition, reorganization, financing, or asset sale, affected Users will receive notice of material changes where required. Other third-party disclosures will occur only with the User’s prior consent or another lawful basis.</p></section>

    <section><h2>Use of Cookies</h2><p>The Website may use Google Analytics cookies. Information generated by those cookies, including the User’s IP address, may be transmitted to and stored by Google on servers in the United States. Google may use the information to evaluate use, prepare activity reports, and provide related services, and may disclose it where required by law or to processors acting on Google’s behalf.</p><p>The User may disable cookies through browser settings, subject to possible loss of functionality, or install the <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer">Google Analytics Opt-out Browser Add-on</a>.</p></section>

    <section><h2>Log Files</h2><p>inlingua may automatically collect IP addresses, browser type, internet service provider, referring and exit pages, operating system, date and time stamps, and clickstream data. This information is used to analyze trends, administer and secure the Website, understand usage, and improve the Services.</p></section>

    <section><h2>Abusive Behavior</h2><p>Disrespectful, abusive, threatening, or aggressive behavior toward trainers, learners, staff, or service providers may result in immediate suspension or termination of access without refund.</p></section>

    <section><h2>Links to Other Websites</h2><p>inlingua is not responsible for the privacy, security, or content practices of third-party websites. The User should review the privacy policy of each linked website before providing information.</p></section>

    <section><h2>Testimonials</h2><p>A testimonial containing personally identifiable information will be posted only with the individual’s prior written consent. A testimonial may be removed upon request to Customer Service or the applicable Center.</p></section>

    <section><h2>Communications from the Website</h2><p>The User may unsubscribe from promotional email using the unsubscribe link in the message. Service-related announcements, including maintenance, security, booking, and account notices, are not optional while the account remains active, except by deactivating the account subject to legal and service obligations.</p></section>

    <section><h2>Content of Services</h2><p>The educational content, learning formats, and other elements of the Services are described on <a href="http://www.myinlinguaboston.com" target="_blank" rel="noopener noreferrer">www.myinlinguaboston.com</a> and in materials supplied by the applicable Center.</p></section>

    <section><h2>Enforcement</h2><p>inlingua monitors ongoing compliance with its privacy directive and these terms and may investigate suspected violations, complaints, misuse, or security incidents and take appropriate corrective action.</p></section>

    <section><h2>Changes to the Privacy Policy</h2><p>Material changes will be communicated by email or by a prominent Website notice before they take effect where required. The User should review this page periodically.</p></section>

    <section><h2>Contact inlingua</h2><p>Questions concerning Part 2 or personal-information practices may be directed to the local Center or to:</p><address><strong>inlingua International Ltd</strong><br/>Belpstrasse 11<br/>CH-3007 Bern, Switzerland<br/>Telephone: <a href="tel:+413138877">+41 (0)31 388 77</a></address><address><strong>inlingua Language School of Boston</strong><br/>36 Baker Road<br/>Everett, MA 02149<br/>Email: <a href="mailto:contact@inlinguabostonma.com">contact@inlinguabostonma.com</a><br/>Telephone: <a href="tel:+16175465590">617-546-5590</a></address></section>

    <section><h2>Protection of Intellectual Property</h2><p>inlingua is the sole owner of its teaching materials and related intellectual property except where expressly stated otherwise. Use of the Services grants no ownership right, title, or interest. The User must not record, reproduce, publish, distribute, or otherwise make available an online learning session or related material without prior written authorization.</p></section>

    <section><h2>Law and Jurisdiction</h2><p>Part 2 is governed by Swiss law. Disputes relating to Part 2 are subject to the exclusive jurisdiction of the courts of Berne, Switzerland, subject to mandatory rights that cannot lawfully be excluded.</p></section>
  </article>
</main><Footer/></>}
