import type {Metadata} from "next";
import {Header,Footer} from "../components";

export const metadata:Metadata={title:"Privacy Notice for California Residents",description:"California Consumer Privacy Act notice for California residents interacting with inlingua Language School of Boston.",alternates:{canonical:"/california-privacy-notice"}};

const categories=[
  ["A. Identifiers","A real name, alias, postal address, unique personal identifier, online identifier, internet protocol address, email address, account name, Social Security number, driver’s license number, passport number, or other similar identifiers."],
  ["B. California Customer Records categories","A name, signature, Social Security number, physical characteristics or description, address, telephone number, passport number, driver’s license or state identification number, insurance policy number, education, employment, employment history, bank-account number, credit-card number, debit-card number, or other financial, medical, or health-insurance information."],
  ["C. Protected classification characteristics","Age (40 years or older), race, color, ancestry, national origin, citizenship, religion or creed, marital status, medical condition, physical or mental disability, sex, gender, gender identity or expression, sexual orientation, veteran or military status, and genetic information."],
  ["D. Commercial information","Records of personal property, products or services purchased, obtained, or considered, or other purchasing or consuming histories or tendencies."],
  ["E. Biometric information","Physiological, biological, or behavioral characteristics, including imagery of the iris, retina, fingerprint, face, hand, palm, voice recordings, keystroke patterns, gait patterns, or other information used to establish identity."],
  ["F. Internet or network activity","Browsing history, search history, and information regarding interaction with a website, application, or advertisement."],
  ["G. Geolocation data","Physical location or movements."],
  ["H. Sensory data","Audio, electronic, visual, thermal, olfactory, or similar information."],
  ["I. Professional or employment information","Current or past job history, performance evaluations, or other professional information."],
  ["J. Non-public education information (FERPA)","Education records directly related to a student and maintained by an educational agency, institution, or party acting on its behalf, including grades, transcripts, class lists, schedules, student identification codes, financial information, or disciplinary records."],
  ["K. Inferences drawn from other personal information","Profiles reflecting preferences, characteristics, psychological trends, predispositions, behavior, attitudes, intelligence, abilities, or aptitudes."],
];

export default function CaliforniaPrivacyNoticePage(){return <><Header/><main id="main" className="policy-page ccpa-page">
  <header className="policy-hero"><div className="shell"><p className="eyebrow">CALIFORNIA PRIVACY RIGHTS</p><h1>Privacy Notice for California Residents</h1><p>Effective September 8, 2021</p></div></header>
  <article className="policy-content shell">
    <section><p>This Privacy Notice for California Residents (the “Notice”) supplements the information contained in the general <a href="/privacy-policy">Privacy Policy</a> of inlingua Language School of Boston and applies solely to visitors, users, and others who reside in the State of California. We adopted this Notice to comply with the California Consumer Privacy Act of 2018 (the “CCPA”). Terms defined in the CCPA have the same meaning when used in this Notice.</p></section>

    <section><h2>Definitions</h2><dl className="policy-definitions"><dt>Website</dt><dd>The website located at <a href="https://inlinguabostonma.com">https://inlinguabostonma.com</a> and related pages operated for inlingua Language School of Boston.</dd><dt>Owner or “We”</dt><dd>inlingua Language School of Boston, the owner or operator responsible for the Website and the personal information described in this Notice.</dd><dt>User or “You”</dt><dd>A California resident who visits, interacts with, submits information through, or otherwise uses the Website or related services.</dd></dl></section>

    <section><h2>Information We Collect</h2><p>The Website collects information that identifies, relates to, describes, references, is reasonably capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular consumer or household (“personal information”) as defined by the CCPA.</p><p>The following table describes categories of personal information that we have collected from consumers within the preceding 12 months:</p><div className="policy-table-wrap"><table className="policy-data-table"><thead><tr><th>Category</th><th>Examples</th><th>Collected</th></tr></thead><tbody>{categories.map(([category,examples])=><tr key={category}><th scope="row">{category}</th><td>{examples}</td><td><strong>YES</strong></td></tr>)}</tbody></table></div><p>Personal information does not include publicly available information from government records, deidentified or aggregated consumer information, or information excluded from the CCPA’s scope by applicable law.</p><p>We obtain the categories of personal information listed above:</p><ul><li><strong>Directly from You</strong>, including information supplied through forms, registrations, inquiries, transactions, or communications; and</li><li><strong>Indirectly from You</strong>, including information obtained from observing actions on the Website or interactions with services, advertisements, or communications.</li></ul></section>

    <section><h2>Use of Personal Information</h2><p>We may use or disclose personal information for one or more of the following business purposes:</p><ul><li>To fulfill or meet the reason for which the information was provided, including responding to requests, inquiries, registrations, or service needs;</li><li>To process transactions, payments, bookings, and related records, and to detect or prevent fraud;</li><li>To provide customer service, account support, troubleshooting, security, and service communications;</li><li>To comply with applicable laws, regulations, legal process, governmental requests, and internal compliance obligations; and</li><li>To evaluate or complete a merger, restructuring, reorganization, dissolution, or sale or transfer of some or all assets.</li></ul><p>We will not collect additional categories of personal information or use collected personal information for materially different, unrelated, or incompatible purposes without providing notice as required by law.</p></section>

    <section><h2>Sharing Personal Information</h2><p>We may disclose personal information to a third party for a business purpose. Business-purpose disclosures are made under contracts that describe the purpose and require the recipient to keep the information confidential and use it only to perform the contracted services or as otherwise permitted by law.</p><p>We may share personal information with the following categories of third parties:</p><ul><li>Service providers; and</li><li>Data aggregators.</li></ul></section>

    <section><h2>Your Rights and Choices</h2><p>The CCPA provides California residents with specific rights regarding personal information, subject to applicable limitations and exceptions.</p><h3>Access to Specific Information and Data Portability Rights</h3><p>Upon receipt and confirmation of a verifiable consumer request, we may disclose:</p><ul><li>The categories of personal information collected about You;</li><li>The categories of sources for that personal information;</li><li>The business or commercial purpose for collecting or selling that information;</li><li>The categories of third parties with whom we share that information;</li><li>The specific pieces of personal information collected about You; and</li><li>If applicable, separate lists identifying categories of information sold and categories disclosed for a business purpose, together with the relevant recipient categories.</li></ul>
    <h3>Deletion Request Rights</h3><p>You may request deletion of personal information collected from and retained about You, subject to exceptions. We may deny a deletion request where retaining the information is necessary to:</p><ul><li>Complete the transaction for which it was collected, provide requested goods or services, or otherwise perform a contract;</li><li>Detect security incidents; protect against malicious, deceptive, fraudulent, or illegal activity; or prosecute those responsible;</li><li>Debug products to identify and repair errors that impair intended functionality;</li><li>Comply with a legal obligation, lawful investigation, court order, or applicable law; or</li><li>Make other internal and lawful uses compatible with the context in which You provided the information.</li></ul>
    <h3>Exercising Access, Data Portability, and Deletion Rights</h3><p>To exercise the access, data-portability, or deletion rights described above, submit a verifiable consumer request by:</p><ul><li>Calling <a href="tel:+16178747477">(617) 874-7477</a>; or</li><li>Emailing <a href="mailto:inlingua.boston@inlingua.com">inlingua.boston@inlingua.com</a>.</li></ul><p>Only You, or a person registered with the California Secretary of State whom You authorize to act on Your behalf, may make a verifiable request related to Your personal information. A parent or legal guardian may make a request on behalf of a minor child.</p><p>You may submit a request to know or for data portability only twice within a 12-month period. The request must provide sufficient information to allow us reasonably to verify that You are the person about whom we collected personal information, or an authorized representative, and must describe the request with sufficient detail to permit us to understand, evaluate, and respond to it.</p>
    <h3>Response Timing and Format</h3><p>We endeavor to respond to a verifiable consumer request within 45 days of receipt. If additional time is reasonably necessary, we will inform You in writing of the reason and extension period. We will deliver our written response by mail or electronically, at Your option where applicable.</p><p>Disclosures will cover only the 12-month period preceding receipt of the verifiable request. If we cannot comply, our response will explain the applicable reason. We do not charge a fee unless a request is excessive, repetitive, or manifestly unfounded. If a fee is warranted, we will explain the basis and provide a cost estimate before completing the request.</p></section>

    <section><h2>Personal Information Sales</h2><p>We do not sell personal information. If our practices change, we will provide notice and honor applicable opt-in and opt-out rights before selling personal information, including special protections applicable to minors.</p></section>

    <section><h2>Non-Discrimination</h2><p>We will not discriminate against You for exercising CCPA rights. In particular, we will not deny goods or services, charge different prices or rates, impose penalties, provide a different level or quality of service, or suggest that You may receive different pricing or service quality solely because You exercised a CCPA right, except as otherwise permitted by law.</p></section>

    <section><h2>Other California Privacy Rights</h2><p>California’s “Shine the Light” law, Civil Code section 1798.83, may permit California residents with an established business relationship to request information regarding certain disclosures of personal information to third parties for their direct-marketing purposes during the preceding calendar year. To submit such a request, contact us using the information below and state that the request concerns “California Shine the Light.”</p></section>

    <section><h2>Changes to Our Privacy Notice</h2><p>We reserve the right to amend this Notice at our discretion and at any time. When changes are made, we will post the updated Notice on the Website and revise the effective date. Continued use of the Website after posting constitutes acknowledgment of the updated Notice to the extent permitted by law.</p></section>

    <section><h2>Contact Information</h2><p>Questions or comments about this Notice, the ways in which we collect and use information, Your choices and rights, or a request under California law may be directed to:</p><address><strong>inlingua Language School of Boston</strong><br/>Telephone: <a href="tel:+16178747477">(617) 874-7477</a><br/>Website: <a href="https://inlinguabostonma.com">https://inlinguabostonma.com</a><br/>Email: <a href="mailto:inlingua.boston@inlingua.com">inlingua.boston@inlingua.com</a></address></section>

    <p className="legal-generator-credit">generated by WPLP Legal Pages</p>
  </article>
</main><Footer/></>}
